import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="px-6 py-4 bg-gray-100 mb-6 flex gap-4">
          <Link href="/" className="text-blue-600 font-medium hover:underline">
            Home
          </Link>
          <Link
            href="/about"
            className="text-blue-600 font-medium hover:underline"
          >
            About
          </Link>
          <Link
            href="/bookings"
            className="text-blue-600 font-medium hover:underline"
          >
            Bookings
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
